name: flutter_test_example
description: A Flutter Package (Demo) to render spotlight_ant.
homepage: https://github.com/evan361425/flutter-spotlight-ant

version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  fluttertoast: ^8.1.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  spotlight_ant:
    path: ../
  url_launcher: ^6.1.8
  url_strategy: ^0.2.0
  go_router: ^13.2.2

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/spotlight-ant.png
