name: Built pages

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  gh-page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Get flutter dependencies.
      - name: Install dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Build web
        run: make build-example

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
