name: Publish package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Draft a release in specific tag. Use current commit, will not create tag."
        required: false
  push:
    tags:
      - "v*"

jobs:
  vars:
    name: Get variable
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.result }}
      status: ${{ steps.status.outputs.value }}
      changelog: ${{ steps.changelog.outputs.value }}
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            return context.eventName === 'workflow_dispatch'
              ? '${{ github.event.inputs.tag }}'
              : context.payload.ref.replace(/\/?refs\/tags\//, '');

      - name: Extract status ("prod" or "dev")
        uses: haya14busa/action-cond@v1
        id: status
        with:
          cond: ${{ contains(steps.tag.outputs.result, '-dev') }}
          if_true: "dev"
          if_false: "prod"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract latest changelog
        id: changelog
        run: |
          CHANGELOG=$(cat doc/CHANGELOG_LATEST.md)
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "::set-output name=value::$CHANGELOG"

  update-changelog-and-publish:
    runs-on: ubuntu-latest
    needs:
      - vars
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Extract changelog
        id: changelog
        run: |
          CHANGELOG=$(cat CHANGELOG.md)
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "::set-output name=value::$CHANGELOG"

      - name: Update changelog
        run: |
          CHANGELOG='${{ needs.vars.outputs.changelog }}'
          printf "## ${{ needs.vars.outputs.tag }} $(date +"%F")\n\n$CHANGELOG\n\n" > CHANGELOG.md
          echo "${{ steps.changelog.outputs.value }}" >> CHANGELOG.md

      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit . -m "Bump to ${{ needs.vars.outputs.tag }}"
          git push origin

      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_CREDENTIALS }}

  draft-release:
    runs-on: ubuntu-latest
    needs:
      - vars
    steps:
      - name: Draft release with changelog
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.vars.outputs.tag }}
          release_name: ${{ needs.vars.outputs.tag }}
          body: ${{ needs.vars.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
